# Generated by Django 2.2.14 on 2022-01-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20220118_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('L', 'Laptop'), ('S', 'Smartphone'), ('C', 'Camera')], max_length=1),
        ),
    ]
